#
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "NOASSERTION",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "Zlib",
    "CDLA-Permissive-2.0",
]
workarounds = ["ring"]

[ring]
accepted = ["OpenSSL"]

[xxhash-rust]
accepted = ["BSL-1.0"]

[enquote]
accepted = ["Unlicense"]

[webpki.clarify]
license = "ISC"
files = [
    { path = "LICENSE", checksum = "5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a", license = "ISC" },
]